version: '3.8'

services:
  mysql-ecommerce:
    volumes:
      - ./init-mysql/:/docker-entrypoint-initdb.d
    image: mysql:8.0-debian
    container_name: mysql-ecommerce
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - microservices-net

  eureka-service:
    build:
      context: ./eureka-service
    container_name: eureka-service
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - microservices-net
    depends_on:
      - eureka-service

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8080"
    networks:
      - microservices-net
    environment:
      DATABASE_URL: jdbc:mysql://mysql-ecommerce:3306/${MYSQL_DATABASE_USER}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-ecommerce
      - eureka-service

  product-catalog-service:
    build:
      context: ./product-catalog-service
    container_name: product-catalog-service
    restart: always
    env_file:
      - .env
    ports:
      - "8082:8082"
    networks:
      - microservices-net
    environment:
      DATABASE_URL: jdbc:mysql://mysql-ecommerce:3306/${MYSQL_DATABASE_PRODUCT}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-ecommerce
      - eureka-service

networks:
  microservices-net:
    driver: bridge